<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 phoenix.glb
Author: NORBERTO-3D (https://sketchfab.com/norberto3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/phoenix-bird-844ba0cf144a413ea92c779f18912042
Title: phoenix bird
-->
<script>

  import    {Spring}        from  'svelte/motion';

  import    { Group }       from  'three';
  import    { T }           from  '@threlte/core';
  import    { useGltf, useGltfAnimations, OrbitControls } from '@threlte/extras';
	

  let { fallback,  error,  children, 
        ref =$bindable(),  pxcam=$bindable(false),
        pos=[new Spring(0), new Spring(128), new Spring(256)],
        size, ...props
  } =$props();


  ref = new Group()

  const gltf = useGltf('/assets/phoenix.glb')

  export const {actions,  mixer} =useGltfAnimations(gltf, ref);
  
  //setTimeout(()=> console.table('items: ', $actions['Take 001']), 2000 );
  setTimeout(()=> {$actions['Take 001'].play()}, 3000 );
$effect(_=> console.log('yesser: ',pos))
</script>


{#if pxcam} <T.PerspectiveCamera    
                        makeDefault
                        position ={[0, 48, 48]}
                        oncreate ={ref=> ref.lookAt(1, 2, 1)}
                        near={1}        far={9999}
            >
                    <OrbitControls  target={[0, 0, 0]}
                                    enableDamping />
            </T.PerspectiveCamera>
{/if}

<T is={ref}  dispose={false} {...props}
>
{#await  gltf}  {@render fallback?.()}
{:then  gltf}
<T.Group  name ='Sketchfab_Scene' 
>
 <T.Group   name ='Sketchfab_model' 
            scale={.1}     position={[pos[0].current, pos[1].current, pos[2].current]}
            rotation={[-Math.PI / 2, 0, 0.4]} 
            ondblclick={_=> pxcam=!pxcam}
 >
  <T.Group  name='5f59736c86d4457fa045aec4aea6b7e0fbx' 
            rotation={[Math.PI / 2, 0, 0.3,]}
  >
    <T.Group   name='Object_2'>
     <T.Group name='RootNode' >
      <T.Group name='Object_4' >
        <T is={gltf.nodes._rootJoint} />
        <T.Group name='Object_6' rotation={[-Math.PI / 2, 0, 0,]} />
        <T.Group name='AMesh_Ride_FengHuang_01' rotation={[-Math.PI / 2, 0, 0,]} />
        <T.SkinnedMesh  name='Object_7'   geometry={gltf.nodes.Object_7.geometry} 
                      material={gltf.materials.MatI_Ride_FengHuang_01a}  
                      skeleton={gltf.nodes.Object_7.skeleton}
        />
        <T.SkinnedMesh  name='Object_8'   geometry={gltf.nodes.Object_8.geometry}
                        material={gltf.materials.MatI_Ride_FengHuang_01b}  
                        skeleton={gltf.nodes.Object_8.skeleton} 
        />
      </T.Group>
     </T.Group>
    </T.Group>
  </T.Group>
 </T.Group>
</T.Group>

{:catch err}  {@render error?.({error: err})}
{/await}

{@render children?.({ ref })}
</T>
	